# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d8b46280c3727e17c046749f801efe339614ff8c26bab7002e97381a3a4f1d24a00bc585c98a24243705aa38ecc6835e81d58b8946fee8803aef143bfedfdbb

test:
  secret_key_base: 3d61c1557e51f9dd4a02ba5f7126ce16f7a49bed035e8b09e09df46aa6efa143d0c52edd9330f72dec8c5d2693869ef572a0030dbd7178436f23dbb3482d3832

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
